// This file is auto-generated from secrets/disc.pdf via Apple Vision OCR
export const discPages = [
  {
    "page": 1,
    "title": "TTI",
    "content": "TTI\nSUCCESS\nINSIGHTS.\nTriMetrix® EQ\nManagement-Staff\nKyle Jenkins\nConsultant 2\nImproving Enterprises\n3-20-2015\nA teamwork development partnership between\nClear Cut Strategies, LLC & The Abelson Group\nTel. 937-597-4507 Email-CarlaNeer@hotmail.com\nSucceed@TheAbelsonGroup.com\nCLEAR CUT STRATEGIES\nReplacing Chaos with Results\nCopyright © 2006-2015. Target Training International, Ltd"
  },
  {
    "page": 2,
    "title": "Introduction Where Opportunity Meets Talent®",
    "content": "Introduction Where Opportunity Meets Talent®\nThe TriMetrix® EQ Coaching Report was designed to increase the understanding of an\nindividual's talents. The report provides insight to three distinct areas: behaviors, motivators and\nemotional intelligence. Understanding strengths and weaknesses in each of the three areas will\nlead to personal and professional development and a higher level of satisfaction.\nThe following is an in-depth look at your personal talents in the five main sections:\nBehaviors\nThis section of the report is designed to help you attain a greater knowledge of yourself as well as\nothers. The ability to interact effectively with people may be the difference between success and\nfailure in your work and personal life. Effective interaction starts with an accurate perception of\noneself.\nMotivators\nThis section of the report provides information on the why of your actions, which with application\nand coaching, can tremendously impact your valuing of life. Once you know the motivations that\ndrive your actions, you will immediately be able to understand the causes of conflict.\nIntegrating Behaviors And Motivators\nThis section of the report will help you blend the how and the why of your actions. Once you can\nunderstand how your behaviors and motivators blend together, your performance will be\nenhanced and you will experience an increase in satisfaction.\nEmotional Intelligence Section\nThis section of the report provides information on your emotional intelligence, which with\napplication and coaching, can impact the way you respond to emotionally charged situations. In\nturn you will increase your performance and decision making\nBlending Behaviors, Motivators And EQ\nThis section will illustrate the impact your Emotional Intelligence has on your core behavioral style\nas well as your top two motivators."
  },
  {
    "page": 3,
    "title": "Introduction Behaviors Section",
    "content": "Introduction Behaviors Section\nBehavioral research suggests that the most effective people are those who understand\nthemselves, both their strengths and weaknesses, so they can develop strategies to meet\nthe demands of their environment.\nA person's behavior is a necessary and integral part of who they are. In other words, much of our\nbehavior comes from \"nature\" (inherent), and much comes from \"nurture\" (our upbringing). It is\nthe universal language of \"how we act,\" or our observable human behavior.\nIn this report we are measuring four dimensions of normal behavior. They are:\n• How you respond to problems and challenges.\n• How you influence others to your point of view.\n• How you respond to the pace of the environment.\n•How you respond to rules and procedures set by others\nThis report analyzes behavioral style; that is, a person's manner of doing things. Is the report\n100% true? Yes, no and maybe. We are only measuring behavior. We only report statements\nfrom areas of behavior in which tendencies are shown. To improve accuracy, feel free to make\nnotes or edit the report regarding any statement from the report that may or may not apply, but\nonly after checking with friends or colleagues to see if they agree.\n\"All people exhibit all four behavioral\nfactors in varying degrees of intensity.\"\n-W.M. Marston"
  },
  {
    "page": 4,
    "title": "General Characteristics",
    "content": "General Characteristics\nBased on Kyle's responses, the report has selected general statements to provide a\nbroad understanding of his work style. These statements identify the basic natural\nbehavior that he brings to the job. That is, if left on his own, these statements identify\nHOW HE WOULD CHOOSE TO DO THE JOB. Use the general characteristics to\ngain a better understanding of Kyle's natural behavior.\nKyle is often seen as practical and objective. He doesn't resist change as much\nas he resists being changed. He needs to be an active participant in situations\nthat will impact his work. He can be friendly with others in many situations, but\nprimarily with groups of established friends and associates. He is sociable and\nenjoys the uniqueness of each human being. He likes a consistent pace in his\nlife, not too fast and not too slow. Kyle can be spontaneous and casual in\nfamiliar circumstances. The familiar atmosphere allows spontaneity when he is\nin his comfort zone. He does not always like being placed in competitive\nsituations. He tends to lose the \"team feeling\" when he is involved in direct\ncompetition. He can be discreet and sociable as called for by the situation. He\nlikes to win through persistence. He uses his strong, steady tendencies to\naccomplish his goals. Kyle likes to develop a routine in both his personal and\nprofessional life and will function best when this routine is maintained. He\nsometimes finds it difficult to relax until all the work is completed. Leisure time\nactivities often include friends and family.\nKyle may want to think over major decisions before acting. He must be\nconvinced that actions will produce the desired result. Making plans and\nfollowing those plans is important to him. He is good at analyzing situations\nthat can be felt, touched, seen, heard, personally observed or experienced. His\nmotto is,\n\"facts are facts.\" Once he makes a decision, he can be organized in\ncarrying it out. Kyle is persistent and persevering in his approach to achieving\ngoals. He finds making decisions easier when he knows that others he\nrespects are doing the same thing; he then has a feeling of stability and\n\"family.\" He prefers to plan his work and work his plan. Others may find it\nrefreshing to have him on their team. He adheres to company policy and\ndoesn't break the rules just for the sake of breaking them.\nANALYZER\nIMPLEMENTOR\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nRELATER"
  },
  {
    "page": 5,
    "title": "General Characteristics Continued",
    "content": "General Characteristics Continued\nKyle may guard some information unless he is asked specific questions. He will\nnot willingly share unless he is comfortable with the knowledge he possesses\nabout the topic. Sometimes he will withdraw from a verbal battle. If he feels\nstrong about an issue, he may retreat to gather his resources and then return to\ntake a stand! He usually is considerate, compassionate and accepting of\nothers; however, on some occasions can become stubborn. Stubbornness\nsurfaces when his ideals and beliefs are confronted. He does not enjoy\nconfrontation for confrontation's sake. He feels he can win through patience\nand resolve. Most people see him as being a considerate and modest person.\nHe probably won't try to steal the spotlight from others. He is more motivated\nby logic than emotion. To him, logic represents tangible research. He is\nsomewhat reserved with those he doesn't trust or know. After trust has been\nestablished, he may be open and candid. He can be outgoing at times.\nBasically introverted, he will \"engage\" in social conversation when the occasion\nwarrants.\nIMPLEMENTOR\nANALYZER\nCONDUCTOR\ncOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nRELATER"
  },
  {
    "page": 6,
    "title": "Value to the Organization",
    "content": "Value to the Organization\nThis section of the report identifies the specific talents and behavior Kyle brings to the\njob. By looking at these statements, one can identify his role in the organization. The\norganization can then develop a system to capitalize on his particular value and make\nhim an integral part of the team.\n• Good listener.\n• Objective and realistic.\n• Good at reconciling factions--is calming and adds stability.\n• Patient and empathetic.\n• Builds good relationships.\n• Presents the facts without emotion.\n• Consistent and steady.\nIMPLEMENTOR\nANALYZER\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nRELATER\nCopyright © 2006-2015. Target Training International, Ltd. 5"
  },
  {
    "page": 7,
    "title": "Checklist for Communicating",
    "content": "Checklist for Communicating\nMost people are aware of and sensitive to the ways with which they prefer to be\ncommunicated. Many people find this section to be extremely accurate and important\nfor enhanced interpersonal communication. This page provides other people with a\nlist of things to DO when communicating with Kyle. Read each statement and identify\nthe 3 or 4 statements which are most important to him. We recommend highlighting\nthe most important \"DO's\" and provide a listing to those who communicate with Kyle\nmost frequently.\nWays to Communicate\nBe prepared with the facts and figures.\nUse an unemotional approach.\nShow sincere interest in him as a person. Find areas of common\ninvolvement and be candid and open.\nRespect his quiet demeanor.\nProvide guarantees that his decision will minimize risks; give assurance\nthat provides him with benefits.\nLook for hurt feelings or personal reasons if you disagree.\nProvide a friendly environment.\nGive him time to analyze the data before making a decision.\nPresent your case softly, nonthreateningly with a sincere tone of voice.\nProvide details in writing.\nUse expert testimonials.\nIMPLEMENTOR\nANALYZER\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nRELATER\nCopyright © 2006-2015. Target Training International, Ltd. 6"
  },
  {
    "page": 8,
    "title": "Checklist for Communicating Continued",
    "content": "Checklist for Communicating Continued\nThis section of the report is a list of things NOT to do while communicating with Kyle.\nReview each statement with Kyle and identify those methods of communication that\nresult in frustration or reduced performance. By sharing this information, both parties\ncan negotiate a communication system that is mutually agreeable.\nWays NOT to Communicate\n• Offer assurance and guarantees you can't fulfill.\nMake statements you cannot prove.\nTouch his body when talking to him.\nBe redundant.\nStick coldly or harshly to business; on the other hand, don't lose sight of\ngoals by being too personal.\nBe disorganized\nLeave things open to interpretation.\nManipulate or push him into agreeing because he probably won't fight back.\nDebate about facts and figures.\nPatronize or demean him by using subtlety or incentive.\nPretend to be an expert, if you are not.\nIMPLEMENTOR\nANALYZER\n/26\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nRELATER"
  },
  {
    "page": 9,
    "title": "Communication Tips",
    "content": "Communication Tips\nThis section provides suggestions on methods which will improve Kyle's communications with others. The tips\ninclude a brief description of typical people with whom he may interact. By adapting to the communication style\ndesired by other people, Kyle will become more effective in his communications with them. He may have to\npractice some flexibility in varying his communication style with others who may be different from himself. This\nflexibility and the ability to interpret the needs of others is the mark of a superior communicator.\nWhen communicating with a person who is\ndependent, neat, conservative, perfectionist,\ncareful and compliant:\n• Prepare your \"case\" in advance.\n• Stick to business\n• Be accurate and realistic.\nFactors that will create tension or\ndissatisfaction:\n• Being giddy, casual, informal, loud\n• Pushing too hard or being unrealistic with\ndeadlines.\n• Being disorganized or messy.\nWhen communicating with a person who is\nambitious, forceful, decisive, strong-willed,\nindependent and goal-oriented:\n• Be clear, specific, brief and to the point.\n• Stick to business\n• Be prepared with support material in a\nwell-organized \"package.\"\nFactors that will create tension or\ndissatisfaction:\n• Talking about things that are not relevant to the\nIssue\n• Leaving loopholes or cloudy issues\n• Appearing disorganized.\nWhen communicating with a person who is\npatient, predictable, reliable, steady, relaxed and\nmodest:\n• Begin with a personal comment--break the Ice.\n• Present your case softly, nonthreateningly\n• Ask \"how?\" questions to draw their opinions.\nFactors that will create tension or\ndissatisfaction:\n• Rushing headlong into business.\n• Being domineering or demanding\n• Forcing them to respond quickly to your\nobjectives.\nWhen communicating with a person who is\nmagnetic, enthusiastic, friendly, demonstrative\nand political:\n• Provide a warm and friendly environment.\n• Don't deal with a lot of details (put them in writing).\n• Ask \"feeling\" questions to draw their opinions or\ncomments.\nFactors that will create tension or\ndissatisfaction:\n• Being curt, cold or tight-lipped\n• Controlling the conversation.\n• Driving on facts and figures, alternatives,\nabstractions."
  },
  {
    "page": 10,
    "title": "Perceptions",
    "content": "Perceptions\nSee Yourself as Others See You\nA person's behavior and feelings may be quickly telegraphed to others. This section\nprovides additional information on Kyle's self-perception and how, under certain\nconditions, others may perceive his behavior. Understanding this section will\nempower Kyle to project the image that will allow him to control the situation.\nSelf-Perception\nKyle usually sees himself as being:\n• Considerate\n• Good-Natured\n• Team player\n• Thoughtful\n• Dependable\n• Good listener\nOthers' Perception - Moderate\nUnder moderate pressure, tension, stress or fatigue, others may see him as\nbeing:\n• Nondemonstrative\n• Unconcerned\n• Hesitant\n• Inflexible\nOthers' Perception - Extreme\nUnder extreme pressure, stress or fatigue, others may see him as being:\n• Possessive\n• Stubborn\n?\n• Detached\n• Insensitive\nIMPLEMENTOR\nANALYZER\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nRELATER"
  },
  {
    "page": 11,
    "title": "The Absence of a Behavioral Factor",
    "content": "The Absence of a Behavioral Factor\nThe absence of a behavioral factor may provide insight into situations or environments\nthat may cause tension or stress. Based on research, we are able to identify\nsituations that should be avoided or minimized in a person's day-to-day environment.\nBy understanding the contribution of a low behavioral style, we are able to better\narticulate a person's talents and create environments where people can be more\neffective.\nSituations and circumstances to avoid or aspects needed within the\nenvironment in order to minimize behavioral stress.\n• Avoid situations where forced to trust without supporting data.\n• Avoid work environments that require an open door policy.\n• Avoid giving public presentations, as doing so will cause stress.\nUnderstanding that the need to adapt is unavoidable at times, below are\ntips for adapting to those with I above the energy line and/or tips for\nseeking environments that will be conducive to the low I.\n• Understand when an analytical perspective is needed and valued.\n• Meetings that constantly move off track will cause stress and may\ndecrease effectiveness as a participant.\n• Daily and repetitive team meetings will detract from productivity and add\nto stress.\nIMPLEMENTOR\nANALYZER\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nRELATER\nCopyright © 2006-2015. Target Training International, Ltd. 10"
  },
  {
    "page": 12,
    "title": "Descriptors",
    "content": "Descriptors\nBased on Kyle's responses, the report has marked those words that describe his\npersonal behavior. They describe how he solves problems and meets challenges,\ninfluences people, responds to the pace of the environment and how he responds to\nrules and procedures set by others.\nDriving\nAmbitious\nPioneering\nStrong-Willed\nDetermined\nCompetitive\nDecisive\nVenturesome\nDominance\nCalculating\nCooperative\nHesitant\nCautious\nAgreeable\nModest\nPeaceful\nUnobtrusive\nInspiring\nMagnetic\nEnthusiastic\nPersuasive\nConvincing\nPoised\nOptimistic\nTrusting\nInfluencing\nReflective\nFactual\nCalculating\nSkeptical\nLogical\nSuspicious\nMatter-of-Fact\nIncisive\nRelaxed\nPassive\nPatient\nPossessive\nPredictable\nConsistent\nSteady\nStable\nSteadiness\nMobile\nActive\nRestless\nImpatient\nPressure-Oriented\nEager\nFlexible\nImpulsive\nCautious\nCareful\nExacting\nSystematic\nAccurate\nOpen-Minded\nBalanced Judgment\nDiplomatic\nCompliance\nFirm\nIndependent\nSelf-Willed\nObstinate\nUnsystematic\nUninhibited\nArbitrary\nUnbending\nCopyright © 2006-2015. Target Training International, Ltd. 11"
  },
  {
    "page": 13,
    "title": "Natural and Adapted Style",
    "content": "Natural and Adapted Style\nKyle's natural style of dealing with problems, people, pace of events and procedures\nmay not always fit what the environment needs. This section will provide valuable\ninformation related to stress and the pressure to adapt to the environment.\nProblems - Challenges\nNatural\nKyle is cautious in his approach to\nproblem solving and does not\nattempt to demand that his view, or\nopinion, be accepted at face value.\nKyle likes to solve problems within\nthe framework of a team\nenvironment. He will look for a\ncompromise as opposed to a\nwin-lose situation.\nAdapted\nKyle sees no need to change his\napproach to solving problems or\ndealing with challenges in his present\nenvironment.\nPeople - Contacts\nNatural\nKyle is undemonstrative in his\napproach to influencing others and\nlikes to let facts and figures stand for\nthemselves. He feels persuasion\nneeds to be objective and\nstraightforward. His trust level is\nbased on each interaction--the past\nis the past. He presents facts\nwithout embellishments.\nAdapted\nKyle sees no need to change his\napproach to influencing others to his\nway of thinking. He sees his natural\nstyle to be what the environment is\ncalling for.\nIMPLEMENTOR\nANALYZER\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nRELATER\nCopyright © 2006-2015. Target Training International, Ltd. 12"
  },
  {
    "page": 14,
    "title": "Paco: Conaistency",
    "content": "Paco: Conaistency\nNatural\nKyle is comfortable in an\nenvironment in which there are few\nprojecte going on concurrently. He is\napprecialive of the team concept and\nfeels quite secure in an environment\nwhere the need to move from one\nactivity to another quite quickly is\nhekt to a minimum.\nAdapted\nKyle sees his natural activity style to\nbe just what the environment needs.\nWhat you see is what you get for\nactivity level and consistency\nSometimes he would like the world to\nslow down.\nProcedures - Constraints\nNatural\nKyle naturally is cautious and\nconcerned for quality. He likes to be\non a team that takes responsibility\nfor the final product. He enjoys\nKnewing the rules and can become\nupset when others fail to comply with\nthe rules.\nAdapted\nKyle shows little discomfort when\ncomparing his basic (natural) style to\nhis response to the environment\n(adapted) style. The difference is not\nsignificant and Kyle sees little or no\nneed to change his response to the\nenvironment.\nIMPLEMENTOR\nANALYZER\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nClear Out Strategies, LLC & The Abelson Group\nTel. 937-597-4507 Emait-CariaNeer@hotmail.com\nRELATER\nCopyright © 2006-2015. Target Training International, Ltd. 13"
  },
  {
    "page": 15,
    "title": "Kyle sees his present work environment requiring him to exhibit the behavior listed on",
    "content": "Kyle sees his present work environment requiring him to exhibit the behavior listed on\nthis page. If the following statements DO NOT sound job related, explore the reasons\nwhy he is adapting this behavior.\n• Task focus over people focus.\n• Sensitivity to existing rules and regulations.\n• Diplomatic cooperation in team interaction.\n• Adherence to established guidelines and procedures.\n• Precise, analytical approach to work tasks.\n• Logical solutions.\n• Consistency of task performance.\n• Traditional, quality-oriented work model to follow.\n• Exhibiting patience and good listening skills.\n• Disciplined, meticulous attention to order.\n• Compliance to high standards\n• Using a disciplined approach.\nsaunt\n• Limited contact with people.\nIMPLEMENTOR\nANALYZER\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nRELATER"
  },
  {
    "page": 16,
    "title": "Time Wasters",
    "content": "Time Wasters\nThis section of your report is designed to identify time wasters that may impact your\noverall time use effectiveness. Possible causes and solutions will serve as a basis for\ncreating an effective plan for maximizing your use of TIME and increasing your\nPERFORMANCE.\nFailure To Share Information -\nThe failure to share information is the inability or unwillingness to discuss with\nothers.\nPossible Causes:\n• Don't think others want to know the information\n• Unclear of the way the information will be used/received\n• Wait until asked before sharing information\nPossible Solutions:\n• Let others know that they need to ask for information\n• Share with those whose opinions you trust\nResisting Change\nResisting change is the process of consciously or subconsciously not\nparticipating in the change process. Measures of resistance may be active or\npassive, not doing things the new way, or making excuses for not having tasks\naccomplished.\nPossible Causes:\n• Need a high degree of security\n• Like to maintain the status quo\n• Routine/procedures have worked in the past\n• One specific aspect of a proposed change violates sense of values\n• A specific change is not seen as contributing to successful\naccomplishments\nPossible Solutions:\n• Acknowledge that change is a natural part of any job\nIMPLEMENTOR\nANALYZER\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nRELATER\nCopyright © 2006-2015. Target Training International, Ltd. 15"
  },
  {
    "page": 17,
    "title": "Time Wasters Continued",
    "content": "Time Wasters Continued\n• Develop the habit of writing down all of the pros and cons of a specific\nchange\n• Evaluate each objection to a change\n• If there is one specific objection that is overriding the ability to change,\nshare the specific concern with those involved and seek advice or input\nfrom others\nPostpone The Unpleasant /\nPostponing the unpleasant is similar to procrastinating but is usually a\ncontinual reprioritizing of daily tasks. It is often a way to delay something that\nis not enjoyable.\nPossible Causes:\n• Like low-conflict environments and relationships\n• Want to feel the success of accomplishment so the simple tasks are done\nfirst\nPossible Solutions:\n• Change your routine and, for one week, do the unpleasant tasks first\n• See the accomplishment of unpleasant tasks as an equal or even greater\nachievement of success\n• Reward yourself for every unpleasant task that you complete without\npostponing\n• Confront those people who are causing you discomfort and discuss the\nproblems\nHabits X\nA habit is a specific thought, behavior or way of doing something that was\nacquired by repetition or by reinforcement from self and/or others.\nPossible Causes:\n• Have established routines that are comfortable\n• Routine creates a feeling of security\n• Resist change for change's sake\n• Have been praised repeatedly for a specific behavior\nIMPLEMENTOR\nANALYZER\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nRELATER\nCopyright © 2006-2015. Target Training International, Ltd. 16"
  },
  {
    "page": 18,
    "title": "Time Wasters Continued",
    "content": "Time Wasters Continued\nPossible Solutions:\n• Evaluate habits and decide which contribute to your accomplishments and\nwhich deter you from success\n• Try new ways of performing a certain task\n• Ask others for recommendations on different approaches\n• Consciously practice changing your routine\nNot Exercising Authority\nNot exercising authority is the inability to make decisions that might adversely\nimpact some people and compromises the success of task accomplishment. It\nis also the resistance to making the tough calls.\nPossible Causes:\n• Want to be seen as supportive\n• Believe people will do what is right\n• Fear offending others\n• Fear creating conflict between team members\nPossible Solutions:\n• Have clearly defined and written performance objectives\n• Have clearly written rationale for specific decisions\n• Assign decision reporting to the deputy/assistant\n• Appoint a strong deputy or assistant\n• Have a \"Good Guy/Bad Guy\" image agreement with deputy/assistant\nFailure To Anticipate X\nFailure to anticipate is the lack of focusing on possible outcomes or\nrequirements.\nPossible Causes:\n• Expect only the best to happen\n• Expect everyone else to do their best\nANALYZER\nIMPLEMENTOR\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nRELATER\nCopyright © 2006-2015. Target Training International, Ltd. 17"
  },
  {
    "page": 19,
    "title": "Time Wasters Continued",
    "content": "Time Wasters Continued\n• Trust the system to run well\n• Focus on the here and now rather than the future\n• Resist change\nPossible Solutions:\n• Set aside a specific amount of time each day to consider outcome\npossibilities\n• Talk with others who may have prior experience with a specific task or\nperson\nIMPLEMENTOR\nANALYZER\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nRELATER\nCopyright © 2006-2015. Target Training International, Ltd. 18"
  },
  {
    "page": 20,
    "title": "Areas for Improvement",
    "content": "Areas for Improvement\nIn this area is a listing of possible limitations without regard to a specific job. Review\nwith Kyle and cross out those limitations that do not apply. Highlight 1 to 3 limitations\nthat are hindering his performance and develop an action plan to eliminate or reduce\nthis hindrance.\nKyle has a tendency to:\n• Dislike change if he feels the change is unwarranted\n• Not let others know where he stands on an issue.\n• Need help in prioritizing new assignments.\n• Have difficulty establishing priorities. Have a tendency to make all things\na number one priority--may have trouble meeting deadlines.\n• Avoid accountability by overstating the complexity of the situation.\n• Hold a grudge if his personal beliefs are attacked.\n• Be dependent on others for decisions, even if he knows he is right.\nIMPLEMENTOR\nANALYZER\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSUPPORTER\nPROMOTER\nRELATER\nCopyright © 2006-2015. Target Training International, Ltd. 19"
  },
  {
    "page": 21,
    "title": "Behavioral Hierarchy",
    "content": "Behavioral Hierarchy\nYour observable behavior and related emotions contribute to your success on the job.\nWhen matched to the job, they play a large role in enhancing your performance. The\nlist below ranks your behavioral traits from the strongest to the weakest.\n1. Following Policy - Complying with the policy or if no policy.\ncomplying with the way it has been done.\n10.0\n6.9*\n2. Follow Up and Follow Through - A need to be thorough.\n9.7\n6.3*\n3. Consistency - The abiity to do the job the same way.\n9.5\n6.5*\n4. Organized Workplace - Systems and procedures followed for\nsuccess.\n9.0\n5.2*\n5. Analysis of Data - Information is maintained accurately for repeated\nexamination as required.\n9.0\n5.5*\n6. Customer Relations - A desire to convey your sincere interest in\nthem.\n6.8\n6.6*\n7. People Oriented - Spending a high percentage of time successfully\nworking with a wide range of people from diverse backgrounds to\nachieve \"win-win\" outcomes.\n6.0\n6.8*\n* 68% of the population falls within the shaded area\nIMPLEMENTOR\nANALYZER\nCONDUCTOR\nCOORDINATOR\nSUPPORTER\nPROMOTER\nRELATER\nCopyright © 2006-2015. Target Training International, Ltd. 20"
  },
  {
    "page": 22,
    "title": "Behavioral Hierarchy",
    "content": "Behavioral Hierarchy\n8. Frequent Interaction with Others - Dealing with multiple\ninterruptions on a continual basis, always maintaining a friendly\ninterface with others.\n6.2*\n9. Competitiveness - Tenacity, boldness, assertiveness and a \"will to\nwin\" in all situations.\n4.7*\n10. Versatility - Bringing together a multitude of talents and a\nWillingness to adapt the talents to changing assignments as required.\n5.3*\n11. Frequent Change - Moving easily from task to task or being asked\nto leave several tasks unfinished and easily move on to the new task\nwith little or no notice.\n5.2*\n12. Urgency - Decisiveness, quick response and fast action.\n3.0\n3.0\n2.5\n2.2\n2.0\n4.3*\nANALYZER\nIMPLEMENTOR\nCONDUCTOR\nCOORDINATOR\nPERSUADER\nSIA: 24-24-84-77 (20)\nSIN: 26-24-89-74 (20)\n* 68% of the population falls within the shaded area.\nSUPPORTER\nPROMOTER\nRELATER\nCopyright © 2006-2015. Target Training International, Ltd. 21"
  },
  {
    "page": 23,
    "title": "Style Insights® Graphs",
    "content": "Style Insights® Graphs\n3-20-2015\nGraph I\nNatural Style\nGraph I|\nD\nS\nC\nD\nC\n% 24\n24 84 77\n% 26\nNorm 2015 R4\nT: 8:26\nCopyright © 2006-2015. Target Training International, Ltd. 22"
  },
  {
    "page": 24,
    "title": "The Success Insights® Wheel",
    "content": "The Success Insights® Wheel\nThe Success Insights® Wheel is a powerful tool popularized in Europe. In addition to the text you\nhave received about your behavioral style, the Wheel adds a visual representation that allows you\n• View your natural behavioral style (circle).\n• View your adapted behavioral style (star).\n• Note the degree you are adapting your behavior.\n• If you filled out the Work Environment Analysis, view the relationship of your behavior to your\nNotice on the next page that your Natural style (circle) and your Adapted style (star) are plotted on\nthe Wheel. If they are plotted in different boxes, then you are adapting your behavior. The further\nthe two plotting points are from each other, the more you are adapting your behavior.\nIf you are part of a group or team who also took the behavioral assessment, it would be\nadvantageous to get together, using each person's Wheel, and make a master Wheel that\ncontains each person's Natural and Adapted style. This allows you to quickly see where conflict\ncan occur. You will also be able to identify where communication, understanding and\nappreciation can be increased\nCopyright © 1992-2015. Target Training International, Ltd. 23"
  },
  {
    "page": 25,
    "title": "The Success Insights Wheel",
    "content": "The Success Insights Wheel\n3-20-2015\nC\nD\nANALYZER\nCOORDINATOR\nSUPPORTER\nS\nIMPLEMENTOR\nRELATER\nCONDUCTOR\nPROMOTER\nPERSUADER\nT: 8:26\nAdapted:\nNatural:\n(20) SUPPORTING COORDINATOR\n(20) SUPPORTING COORDINATOR\nNorm 2015 R4\nCopyright O 1992-2015. Target Training International, Ltd. 24"
  },
  {
    "page": 26,
    "title": "Introduction Motivators Section",
    "content": "Introduction Motivators Section\nKnowledge of an individual's motivators help to tell us WHY they do things. A review of an\nindividual's experiences, references, education and training help to tell us WHAT they can\ndo. Behavioral assessments help to tell us HOW a person behaves and performs in the\nwork environment. The Personal Motivators & Engagement report measures the relative\nprominence of six basic interests or motivators (a way of valuing life): Theoretical,\nUtilitarian, Aesthetic, Social, Individualistic and Traditional.\nMotivators help to initiate one's behavior and are sometimes called the hidden motivators\nbecause they are not always readily observed. It is the purpose of this report to help illuminate\nand amplify some of those motivating factors and to build on the strengths that each person\nbrings to the work environment.\nBased on your choices, this report ranks your relative passion for each of the six motivators. Your\ntop two and sometimes three motivators cause you to move into action. You will feel positive\nwhen talking, listening or doing activities that satisfy your top motivators.\nThe feedback you will receive in this section will reflect one of three intensity levels for each of the\nsix motivators.\n• Strong - positive feelings that you need to satisfy either on or off the job.\n• Situational - where your feelings will range from positive to indifferent based on other priorities\nin your life at the time.\nThese motivators tend to become more important as your top\nmotivators are satisfied\n• Indifferent - your feelings will be indifferent when related to your 5th or 6th motivator.\nYour Personal Motivators Ranking\n1st\n2nd\n3rd\n4th\n5th\n6th\nIndividualistic\nAesthetic\nTheoretical\nSocial\nUtilitarian\nTraditional\nStrong\nStrong\nSituational\nSituational\nIndifferent\nIndifferent\nCopyright © 1990-2015. Target Training International, Ltd. 25"
  },
  {
    "page": 27,
    "title": "Individualistic",
    "content": "Individualistic\nThe primary interest for this motivator is POWER, not necessarily politics. Research\nstudies indicate that leaders in most fields have a high power drive. Since competition\nand struggle play a large part in all areas of life, many philosophers have seen power\nas the most universal and most fundamental of motives. There are, however, certain\npersonalities in whom the desire for direct expression of this motive is uppermost; who\nwish, above all, for personal power, influence and renown.\n• Maintaining individuality is strived for in relationships.\n• If necessary, Kyle will be assertive in meeting his own needs.\n• He believes \"if at first you don't succeed try, try again.\"\n• People who are determined and competitive are liked by Kyle.\n• He wants to control his own destiny and display his independence.\n• Kyle believes \"when the going gets tough, the tough get going.\"\n• Kyle has the desire to assert himself and to be recognized for his\naccomplishments.\n• Kyle takes responsibility for his actions.\n• Kyle likes to be in situations that allow him the freedom to control his\ndestiny and the destiny of others. His team's strategy is to attempt to\ndilute outsiders' influence on the results of their goals.\nTHEORETICA\nINDIVIDUALIS\nCopyright © 1990-2015. Target Training International, Ltd. 26"
  },
  {
    "page": 28,
    "title": "Aesthetic",
    "content": "Aesthetic\nA higher Aesthetic score indicates a relative interest in \"form and harmony.\" Each\nexperience is judged from the standpoint of grace, symmetry or fitness. Life may be\nregarded as a procession of events, and each is enjoyed for its own sake. A high\nscore here does not necessarily mean that the incumbent has talents in creative\nartistry. It indicates a primary interest in the artistic episodes of life.\n• Form and harmony provide him with an experience to remember.\n• Kyle uses his aesthetic talent to impress others.\n• Kyle looks for and appreciates the beauty in things.\n• Dressing for success comes naturally to Kyle. He enjoys the latest\ndesigner clothes when he has the funds to purchase them.\n• Decorating his surroundings so they are visually pleasing is enjoyable for\nKyle.\nTHEORETICAL\nINDIVIDUALIST\nCopyright © 1990-2015. Target Training International, Ltd. 27"
  },
  {
    "page": 29,
    "title": "Theoretical",
    "content": "Theoretical\nThe primary drive with this motivator is the discovery of TRUTH. In pursuit of this\ndrive, an individual takes a \"cognitive\" attitude. Such an individual is nonjudgmental\nregarding the beauty or utility of objects and seeks only to observe and to reason.\nSince the interests of the theoretical person are empirical, critical and rational, the\nperson appears to be an intellectual. The chief aim in life is to order and systematize\nknowledge: knowledge for the sake of knowledge.\n• If Kyle is truly interested in a specific subject, or if knowledge of specific\nsubject matter is required for success, then he will take the initiative to\nlearn about that subject in great depth.\n• A job that challenges the knowledge will increase his job satisfaction.\n• Kyle will usually have the data to support his convictions.\n• Kyle will seek knowledge based on his needs in individual situations.\n• In those areas where Kyle has a special interest he will be good at\nintegrating past knowledge to solve current problems.\n• If knowledge of a specific subject is not of interest, or is not required for\nsuccess, Kyle will have a tendency to rely on his intuition or practical\ninformation in this area.\n• Kyle has the potential to become an expert in his chosen field.\nATIONAL\nTHEORETICAL\nINDIVIDUALIST\nCopyright © 1990-2015. Target Training International, Ltd.\n. 28"
  },
  {
    "page": 30,
    "title": "Social",
    "content": "Social\nThose who score very high for this motivator have an inherent love of people. The\nsocial person prizes other people and is, therefore, kind, sympathetic and unselfish.\nThey are likely to find the Theoretical, Utilitarian and Aesthetic attitudes cold and\ninhuman. Compared to the Individualistic motivator, the Social person regards helping\nothers as the only suitable form for human relationships. Research indicates that in its\npurest form, the Social interest is selfless\n• Kyle will definitely attempt to help an individual or group overcome a\npredicament, but only if they have \"touched the right chords\" within him.\n• Kyle's desire to help others (even to his own detriment) or decision not to\nhelp others, is reviewed on an individual basis.\nADITIONAL\nTHEORETICAL\nAESTHETIC\nINDIVIDUALISTI\nCopyright © 1990-2015. Target Training International, Ltd. 29"
  },
  {
    "page": 31,
    "title": "Utilitarian",
    "content": "Utilitarian\nThe Utilitarian score shows a characteristic interest in money and what is useful. This\nmeans that an individual wants to have the security that money brings not only for\nthemselves, but for their present and future family. This motivator includes the\npractical affairs of the business world - the production, marketing and consumption of\ngoods, the use of credit, and the accumulation of tangible wealth. This type of\nindividual is thoroughly practical and conforms well to the stereotype of the average\nbusiness person. A person with a high score is likely to have a high need to surpass\nothers in wealth.\n• Kyle will seek a comfort level in his standard of living and try to maintain\nthat level.\n• Overemphasizing the value of money will bore Kyle and turn him off.\n• There is not a tremendous need for Kyle to have great sums of money.\n• He is motivated by internal beliefs and does not feel compelled to impress\nothers with material things.\n• Kyle will accept his financial situation and not strive to change it.\n• Financial security is not a necessity, but a long-term goal.\n• Kyle will not be swayed or motivated by what he feels are excessive\nmaterial goals.\n• Kyle will use his money to satisfy his true motivation.\n• Kyle will not use money as a scorecard to impress others.\n• Money and material possessions are not a high priority for Kyle.\nCopyright © 1990-2015. Target Training International. Ltd. 30"
  },
  {
    "page": 32,
    "title": "Traditional",
    "content": "Traditional\nThe highest interest for this motivator may be called \"unity,\" \"order,\" or \"tradition.\"\nIndividuals with high scores for this motivator seek a system for living. This system\ncan be found in such things as conservatism or any authority that has defined rules.\nregulations and principles for living\n• Kyle's passion in life will be found in one or two of the other dimensions\ndiscussed in this report.\n• It may be hard to manipulate Kyle because he has not defined a\nphilosophy or system that can provide immediate answers to every\nsituation.\n• Kyle can be creative in interpreting other systems or traditions and\nselective in applying those traditions.\n• He will not be afraid to explore new and different ways of interpreting his\nown belief system.\n• In many cases, Kyle will want to set his own rules which will allow his own\nintuition to guide and direct his actions.\n• Traditions will not place limits or boundaries on Kyle.\n• He will work within a broadly defined set of beliefs.\nTHEORETICAL\nAESTHETIC\nINDIVIDUA\nCopyright © 1990-2015. Target Training International, Ltd. 31"
  },
  {
    "page": 33,
    "title": "Navigating Situations Outside Your",
    "content": "Navigating Situations Outside Your\nComfort Zone\nThe information on this page will highlight areas in which you may struggle relating to\nbased on your lowest motivator. The information will teach you how to manage your\nway through discussions focusing on your number six motivator.\nTips for Communicating with \"High Traditional\" utilizing your Individualistic.\nAs you read through the communication tips, think about the following\nquestions:\nHow does the mindset of a high Traditional contribute to today's\nworkforce?\nHow do Traditionals contribute to the world, your professional life\nand your personal life?\nA high Traditional seeks a system for living and wants others to follow the\nsystem of his or her choice.\n• Look at traditions as a way to take what's proven to accomplish goals\nand to enhance them. How can the way things are done be improved,\nwithout throwing out the foundational concepts?\n• Find commonalities between the beliefs of the Traditional and the goals\nbeing accomplish. Can beliefs be utilized to expand influence and\ncontrol?\nOnce a Traditional has made up his or her mind on an issue, he or she will\nrarely change this opinion even if logic indicates he or she is wrong.\n• Persuade the Traditional utilizing shared perspectives and communicate\nthat agreement is not present on all aspects. How can both parties work\ntogether toward a larger common ground and be respectful of each\nother's beliefs.\n• Ask what value is represented in converting the Traditional's thought\nprocess. Understand that extreme biases may be on the table, and\nagreeing to disagree may be necessary in certain areas.\nADITIONAL\nTHEORETICA\nUTILITARIA)\nAESTHETIC\nINDIVIDUALISTIC\nCopyright © 2006-2015. Target Training International, Ltd. 32"
  },
  {
    "page": 34,
    "title": "Navigating Situations Outside Your",
    "content": "Navigating Situations Outside Your\nComfort Zone\nAt times a high Traditional can be overly rigid in evaluating others against his\nor her standard.\n• If alignment between the desired achievement and what the high\nTraditional wants to adhere to can occur, everyone can excel. If\nalignment does not exist on the standards, people will struggle to follow\neither person.\n• People will often feel judged by the high Traditional. How can the desire\nto be seen as a leader be utilized to depersonalize the judgment and\nbring the conversation back to how the organization is going to achieve\nthe goals set before them?\nFor a high Traditional, following proven procedures is more important than\nquick fixes.\nThe proven way will not always grant the most power or project the best\nimage. Ask questions to determine what approach will lead toward the\ndesired legacy. Convince the high Traditional that the right fix will\npreserve the integrity of the foundational principles of the organization.\n• Often times, the quick fix will work and will provide the ideal recognition.\nExplain why this is the choice, and communicate that although the tried\nand true is correct, this will maintain the pillars of the organizational\nfoundation.\nTHEORETICAL\nINDIVIDUALISTIC\nCopyright © 2006-2015. Target Training International, Ltd. 33"
  },
  {
    "page": 35,
    "title": "Motivators - Norms & Comparisons",
    "content": "Motivators - Norms & Comparisons\nFor years you have heard statements like, Different strokes for different folks,\" \"to each his own,\"\nand \"people do things for their own reasons, not yours.\" When you are surrounded by people\nwho share similar motivators, you will fit in with the group and be energized. However, when\nsurrounded by people whose motivators are significantly different from yours, you may be\nperceived as out of the mainstream. These differences can induce stress or conflict. When\nconfronted with this type of situation you can:\n• Change the situation.\n• Change your perception of the situation.\n• Leave the situation.\n• Cope with the situation.\nThis section reveals areas where your motivators may be outside the mainstream and\ncould lead to conflict. The further away you are from the mainstream on the high side, the more\npeople will notice your passion about that motivator. The further away from the mainstream on\nthe low side, the more people will view you as indifferent and possibly negative about that\nmotivator. The shaded area for each motivator represents 68 percent of the population or scores\nthat fall within one standard deviation above or below the national mean.\nNorms & Comparisons Table - Norm 2015\nTheoretical\nMainstream\nUtilitarian\nMainstream\nAesthetic\nMainstream\nSocial\nMainstream\nIndividualistic\nMainstream\nTraditional\nMainstream\n- 68 percent of the population\nI - national mean * - your score\nMainstream - one standard deviation of the national mean\nPassionate - two standard deviations above the national mean\nIndifferent - two standard deviations below the national mean\nExtreme - three standard deviations from the national mean\nCopyright © 2006-2015. Target Training International, Ltd. 34"
  },
  {
    "page": 36,
    "title": "Motivators - Norms & Comparisons",
    "content": "Motivators - Norms & Comparisons\nAll of your attitude scores fall within one standard deviation of the national mean. This means that\n68% of the population have similar attitudes and feelings on each of the six attitudes. Having all\nyour scores close to the national mean indicates the following:\n• You will be seen by others as a team player.\n• You will be able to relate to a large percentage of our society.\n• You will have less conflict with other people.\n• You will have a larger selection of friends and careers than most people.\nCopyright © 2006-2015. Target Training International, Ltd. 35"
  },
  {
    "page": 37,
    "title": "Motivators Hierarchy",
    "content": "Motivators Hierarchy\nYour motivation to succeed in anything you do is determined by your underlying\nmotivators. You will feel energized and successful at work when your job supports\nyour personal motivators. They are listed below from the highest to the lowest.\n1. Individualistic/Political - Rewards those who value personal\nrecognition, freedom, and control over their own destiny and others.\n5.5*\n2. Aesthetic - Rewards those who value balance in their lives, creative\nself-expression, beauty and nature.\n4.3*\n3. Theoretical - Rewards those who value knowledge for knowledge's\nsake, continuing education and intellectual growth.\n6.0\n4. Social - Rewards those who value opportunities to be of service to\nothers and contribute to the progress and well being of society.\n4.2\n5. Utilitarian/Economic - Rewards those who value practical\naccomplishments, results and rewards for their investments of time,\nresources and energy.\n5.3*\n6. Traditional/Regulatory - Rewards those who value traditions\ninherent in social structure,\nrules, regulations and principles.\n4.7*\n5.8\n5.8\n5.5\n5.5\n4.2\n3.2\nTRADITIONAL\nTHEORETICAL\nMI: 45-37-47-45-47-31 (THE.-UTI.-AES.-SOC.-IND.-TRA.)\n* 68% of the population falls within the shaded area.\nAESTHETIC\nINDIVIDUALISTIC\nCopyright © 2006-2015. Target Training International, Ltd. 36"
  },
  {
    "page": 38,
    "title": "Motivation Insights® Graph",
    "content": "Motivation Insights® Graph\n3-20-2015\nScore\nRank\nTHE\n3rd\nUTI.\n5th\nAES\n2nd\nSOC.\n4th\nnational mean\nNorm 2015\nIND\n1st\nTRA.\n6th\nT: 7:04\nCopyright © 2006-2015. Target Training International, Ltd. 37"
  },
  {
    "page": 39,
    "title": "Motivators Wheel™",
    "content": "Motivators Wheel™\n3-20-2015\nTRADITIONAL\n6th\nSOCIAL\n4th\n2nd\nAESTHETIC\nT: 7:04\nSucceed@TheAbeisonGroup.com\nTHEORETICAL\n3rd\n5th\nUTILITARIAN\n1st\nINDIVIDUALISTIC\nCopyright © 2006-2015. Target Training International, Ltd. 38"
  },
  {
    "page": 40,
    "title": "Introduction Integrating Behaviors and Motivators Section",
    "content": "Introduction Integrating Behaviors and Motivators Section\nThe ultimate power behind increasing job satisfaction and performance comes from the blending\nof your behaviors and motivators. Each individually is powerful in order to modify your actions,\nbut the synergy of blending the two moves you to a whole new level.\nIn this section you will find:\n• Potential Behavioral and Motivational Strengths\n• Potential Behavioral and Motivational Conflict\n• Ideal Environment\n• Keys to Motivating\n• Keys to Managing\nCopyright © 2006-2015. Target Training International, Ltd. 39"
  },
  {
    "page": 41,
    "title": "Potential Behavioral and Motivational",
    "content": "Potential Behavioral and Motivational\nStrengths\nThis section describes the potential areas of strengths between Kyle's behavioral style\nand top two motivators. Identify two to three potential strengths that need to be\nmaximized and rewarded in order to enhance on-the-job satisfaction.\n• Will take a firm stance when his position or status is questioned.\n• The ideal right hand to a goal-driven leader.\n• Patient with and willing to listen to the feelings of others.\n• The \"glue\" that ties multiple visions together.\n• Gives clear instruction to what he needs to accomplish goals.\n• Does everything to the best of his ability and is known for this trait.\n• Gives clear specific instructions to maintain balance.\n• Lets his work demonstrate his uniqueness, rather than talking about\nhimself.\nCopyright © 2006-2015. Target Training International, Ltd. 40"
  },
  {
    "page": 42,
    "title": "Potential Behavioral and Motivational",
    "content": "Potential Behavioral and Motivational\nConflict\nThis section describes the potential areas of conflict between Kyle's behavioral style\nand top two motivators. Identify two to three potential conflicts that need to be\nminimized in order to enhance on-the-job performance.\n• Will hide emotions until others push his buttons or take advantage of him.\n• Listens to others but wants to act to his own interest.\n• Dislikes unwarranted change in his environment because of the disruption\nof balance.\nNot willing to share opinions until comfortable about how others will\nreceive it.\n• Nothing is good enough, unless it's the best.\n• He will only feel effective when he can accomplish his agenda through\nstructure.\n• Has trouble starting a new project that conflicts with the harmony of the\norganization.\n• May feel his view is the only way and not see the subjectivity in his\nviewpoint.\nCopyright © 2006-2015. Target Training International, Ltd. 41"
  },
  {
    "page": 43,
    "title": "Ideal Environment",
    "content": "Ideal Environment\nThis section identifies the ideal work environment based on Kyle's basic style and top\ntwo motivators.\nPeople with limited flexibility will find themselves uncomfortable\nworking in any job not described in this section. People with flexibility use intelligence\nto modify their behavior and can be comfortable in many environments. Use this\nsection to identify specific duties and responsibilities that Kyle enjoys and also those\nthat create frustration.\n• Close relationship with a small group of associates.\n• Assignments that can be followed through to completion.\n• An environment dictated by logic rather than emotion. :\n• An environment where detail orientation and processes create\norganizational symmetry.\n• Ability to complete projects and tasks through a stable and harmonious\nteam.\n• An environment that supports time tested, proven processes for\ncompleting tasks.\n• Desires to be seen as the gatekeeper of information and sensitive\nmaterials.\n• Rewards for strict adherence to processes and procedures.-\n• Ability to control the review and storage of facts and data.\nCopyright © 2006-2015. Target Training International, Ltd. 42"
  },
  {
    "page": 44,
    "title": "Keys to Motivating",
    "content": "Keys to Motivating\nThis section of the report was produced by analyzing Kyle's wants. People are\nmotivated by the things they want; thus wants that are satisfied no longer motivate\nReview each statement produced in this section with Kyle and highlight those that are\npresent \"wants.\"\nKyle wants:\n• Constant appreciation, and a feeling of security on the team. /\n• To be recognized for his continuance of quality work.\n• A manager who follows the company policies.\n• Complete and precise systems and procedures that create a harmonious\nworkplace.\n• To support company morale and harmonious causes\n• A proper work/life balance and a physical space that feels like home.\n• The power to protect those he trusts or is loyal to.\n• Appreciation for following procedures and protocol and how that protects\nthe organization's image.\n• Recognition for calculated risk-taking and plans for action\nCopyright © 2006-2015. Target Training International, Ltd. 43"
  },
  {
    "page": 45,
    "title": "Keys to Managing",
    "content": "Keys to Managing\nIn this section are some needs which must be met in order for Kyle to perform at an\noptimum level. Some needs can be met by himself, while management must provide\nfor others. It is difficult for a person to enter a motivational environment when that\nperson's basic management needs have not been fulfilled. Review the list with Kyle\nand identify 3 or 4 statements that are most important to him. This allows Kyle to\nparticipate in forming his own personal management plan.\nKyle needs:\n• Reassurances that he is doing the job right\n• Performance appraisals on a regular basis.\n• A manager who prefers quality over quantity\n• Be provided opportunities to express and change dysfunctional working\nconditions\n• Help understanding chain of command when there are issues he needs to\naddress. 1\n• Help understanding the need to actively engage in new assignments to\npromote balance in the organization.\n• To be in control of information and how it's utilized in achieving company\nobjectives.\n• A manager that understands his strong stance on issues is out of\nprotecting the image of the organization. v\n• To set goals that are in reach. V\nCopyright © 2006-2015. Target Training International, Ltd. 44"
  },
  {
    "page": 46,
    "title": "Introduction Emotional Intelligence Section",
    "content": "Introduction Emotional Intelligence Section\nThe Emotional Quotient ™ report looks at a person's emotional intelligence, which is the ability to\nsense, understand and effectively apply the power and acumen of emotions to facilitate higher\nlevels of collaboration and productivity. The report was designed to provide insight into two broad\nareas: Intrapersonal and Interpersonal emotional intelligence.\nResearch shows that successful leaders and superior performers have well developed emotional\nintelligence skills. This makes it possible for them to work well with a wide variety of people and\nto respond effectively to the rapidly changing conditions in the business world. In fact, a person's\n(EQ) emotional intelligence may be a better predictor of success performance than intelligence\n(IQ).\nThis report measures five dimensions of emotional intelligence:\nIntrapersonal emotional intelligence\nWhat goes on inside of you as you experience day-to-day events.\nSelf-Awareness is the ability to recognize and understand your moods, emotions and drives, as\nwell as their effect on others.\nSelf Regulation is your ability to control or redirect disruptive impulses and moods and the\npropensity to suspend judgment to think before acting.\nMotivation is a passion to work for reasons that go beyond money or status and a propensity to\npursue goals with energy and persistence.\nInterpersonal emotional intelligence\nWhat goes on between you and others.\nEmpathy is your ability to understand the emotional makeup of other people.\nSocial Skills is a proficiency in managing relationships and building networks.\nIs the report 100% true? Yes, no and maybe. We are only measuring emotional intelligence. We\nonly report statements from areas in which tendencies are shown. To improve accuracy, feel free\nto make notes or edit the report regarding any statement from the report that may or may not\napply, but only after checking with friends or colleagues to see if they agree.\nCopyright © 2015, Dr. Izzy Justice and Target Training International, Ltd. 45"
  },
  {
    "page": 47,
    "title": "General Characteristics",
    "content": "General Characteristics\nBased on Kyle's responses, the report has selected general statements to\nprovide a broad understanding of his level of emotional intelligence.\nSelf-Awareness\n• May have trouble articulating unique strengths and/or weaknesses due\nto not understanding the impact of his emotional state.\n• May rely too heavily on feedback from others about his work or in\ndefining who he is.\n• May lack self-confidence, which could make it more difficult to express\nhis true emotions.\nSelf-Regulation\n• Coworkers may perceive him as someone who doesn't handle feedback\nwell, which may limit his opportunities for receiving information.\n• May introduce unnecessary conflict when working with others.\n• May have trouble remaining calm during emotionally charged situations.\nMotivation\n• May tend to give up when faced with a challenge or resistance.\n• May not actively seek out creative challenges.\n• May depend on multi-tasking, making his individual work style less\nefficient than possible.\nEmpathy\n• May have difficulty building trust and respect with others.\n• May hinder group brainstorming sessions or team meetings because he\nmay have difficulty creating an emotionally safe environment.\n• When he holds a strong opinion, he may have trouble considering\nothers' perspectives on the matter.\nSocial Skills\n• May consider task-based work as more important than work that\nrequires him to build relationships.\n• May need an additional support network in times of stress.\n• May find it difficult to read another's body language.\nCopyright © 2015, Dr. Izzy Justice and Target Training International, Ltd. 46"
  },
  {
    "page": 48,
    "title": "Emotional Quotient Assessment Results",
    "content": "Emotional Quotient Assessment Results\nThe Emotional Quotient (EQ) is a measure of your ability to sense,\nunderstand, and effectively apply the power and acumen of your emotions and\nthe emotions of others in order to facilitate high levels of collaboration and\nproductivity. Your overall score on the Emotional Quotient Assessment\nindicates your level of overall emotional intelligence. The higher the number,\nthe more emotionally intelligent you are. If your goal is to raise your EQ, the\ncomponents on which you have scored the lowest should be the focus of your\ndevelopment.\n1. SELF-AWARENESS - The ability to recognize and understand your\nmoods, emotions and drives, as well as their effect on others.\n3.0\n7.4\n2. SELF-REGULATION - The ability to control or redirect disruptive\nimpulses and moods and the propensity to suspend judgment and think\nbefore acting\n5.5\n7.2\n3. MOTIVATION - A passion to work for reasons that go beyond money or\nstatus, and a propensity to pursue goals with energy and persistence.\n6.2\n7.9*\n4. EMPATHY - The ability to understand the emotional makeup of other\npeople.\n4.7\n7.5*\n5. SOCIAL SKILLS - A proficiency in managing relationships and building\nnetworks.\n5 6\n3.6\n7.6*\n* 68% of the population falls within the shaded area.\nCopyright © 2015, Dr. Izzy Justice and Target Training International, Ltd. 47"
  },
  {
    "page": 49,
    "title": "Emotional Quotient Scoring Information",
    "content": "Emotional Quotient Scoring Information\nThe sum of the Self-Regulation, Self-Awareness, and Motivation subscales\nadd up to represent your Intrapersonal Emotional Quotient. The sum of the\nEmpathy and Social Skills subscales add up to represent your Interpersonal\nEmotional Quotient. Your total level of Emotional Quotient was calculated by\nsumming the Intrapersonal and Interpersonal scores.\nINTRAPERSONAL - The ability to understand yourself and form an\naccurate concept of yourself to operate effectively in life.\n5.0\n7.5\nINTERPERSONAL - The ability to understand other people, what\nmotivates others, how they work and how to work cooperatively with them.\n4.2\n7.6*\nTOTAL EMOTIONAL QUOTIENT - Your total level of emotional\nintelligence, formed by combining your intrapersonal and interpersonal\nscores.\n4.7\n7.5*\nCopyright © 2015, Dr. Izzy Justice and Target Training International, Ltd. 48"
  },
  {
    "page": 50,
    "title": "Intrapersonal Self-Awareness",
    "content": "Intrapersonal Self-Awareness\nThe ability to recognize and understand your moods, emotions and drives, as well as\ntheir effect on others\nYou scored a 3.0.\nYou may find it hard to identify and express your emotions which may impact\nyour decisions.\nBecause of your level of self-awareness, you may not have a\nrealistic assessment of yourself.\nWhat you can do:\n• Practice self-reflection by identifying and naming your current emotional\nstate.\n• To improve decision-making, look for trends in your behavior and seek\nto recognize what prompts your reactions.\n• Reflect on how your emotions influence your behavior.\n• Identify how negative or hurtful behavior triggers your emotions.\n• To improve your ability to self-assess, ask a family member, friend or\ntrusted advisor to describe your strengths and weaknesses.\n• Make a list of your strengths and areas for improvement. Look at it\ndaily.\n• Make note of your introspective discoveries and discuss them with a\ntrusted friend or family member.\n• Create an action plan to develop your areas for improvement.\n• Develop self-awareness goals and revisit them at least twice a month.\n(Make sure your goals and action items are SMART - specific,\nmeasurable, actionable, realistic and timelined.)\n• Make note several times a day in a journal about your emotional\nresponses to the current situations to help raise your emotional\nawareness.\nCopyright © 2015, Dr. Izzy Justice and Target Training International, Ltd. 49"
  },
  {
    "page": 51,
    "title": "Intrapersonal Self-Regulation",
    "content": "Intrapersonal Self-Regulation\nThe ability to control or redirect disruptive impulses and moods and the propensity to\nsuspend judgment and think before acting.\nYou scored a 5.5.\nYou would benefit from developing your level of Self-Regulation in order to\nregulate negative emotions and experience positive ones.\nWhat you can do:\n* Practice self-restraint by listening first, pausing and then responding.\n• Learn to step away from difficult or overwhelming situations.\n* Be committed to not interrupting others.\n• When frustration has occurred, summarize the situation to determine\ntriggers.\n• Role-play effective responses to a stressful situation with a family\nmember, friend or trusted co-worker (use examples of workplace\ncircumstances)..\n• Determine activities that improve your mood and take action when you\nfeel stressed or overwhelmed\n• Focus on events that provide a sense of calm or elicit positive emotions.\n• Keep a log of your effective and ineffective self-management skills so\nyou can recall them in future situations.\n• Discuss ways of expressing emotions appropriately with your\nco-workers.\n• When negative emotions take over, try to visualize a positive or calming\nscene.\n• Put things in perspective. Ask yourself, \"What is the worst that can\nhappen?\" or \"How will I feel about this a week from now?\"\nCopyright © 2015, Dr. Izzy Justice and Target Training International, Ltd. 50"
  },
  {
    "page": 52,
    "title": "Intrapersonal Motivation",
    "content": "Intrapersonal Motivation\nA passion to work for reasons that go beyond money or status, and a propensity to\npursue goals with energy and persistence\nYou scored a 6.2.\nYou may occasionally have thoughts along the lines of \"I failed again\" or \"I just\ndon't feel like trying,\" and may tend to have a more pessimistic approach.\nWhat you can do:\n• Set specific goals with dates for achievement.\n• Clarify why the goals you have set are important to you.\n• Define what motivates you by clarifying what you are truly passionate\nabout.\n• Work with a trusted advisor or peer to document your goals and then\ncreate detailed action items to reach them.\n• Set aside time to focus on your passions each day, even if it is just five\nminutes at a time.\n• List your goals and post them where you can see them.\n• Spend time visualizing the outcome of what you are trying to achieve.\n• With friends and family, celebrate accomplishments that bring you closer\nto your goals.\n• Read articles or quotes that inspire you.\n• Question the status quo and make suggestions for improvement.\nCopyright © 2015, Dr. Izzy Justice and Target Training International, Ltd. 51"
  },
  {
    "page": 53,
    "title": "Interpersonal Empathy",
    "content": "Interpersonal Empathy\nThe ability to understand the emotional makeup of other people.\nYou scored a 4.7.\nYou may find it difficult to understand others' emotional responses to situations\nand communication.\nWhat you can do:\n• Attempt to understand others before communicating your point of view.\n• Observe nonverbal behavior to evaluate the negative or positive\nemotions of others.\n• Attempt to see things from others' perspectives before responding to\nyour peers at work or family members.\n• Develop strong interpersonal habits, such as listening to others until they\nare finished with their thought and asking questions versus making\nstatements.\n• Observe body language for nonverbal messages being expressed.\n• Consider how others will feel as a consequence of your actions or\nstatements. Not only what you say, but how you say it.\n• Building empathy can enhance your understanding of people, and\ntherefore may improve your interactions with others.\n• Be genuine about expressing gratitude toward others.\n• Reach out and offer assistance to others; make sure to understand what\nthey are trying to achieve versus turning into your own objective.\nCopyright © 2015, Dr. Izzy Justice and Target Training International, Ltd. 52"
  },
  {
    "page": 54,
    "title": "Interpersonal Social Skills",
    "content": "Interpersonal Social Skills\nA proficiency in managing relationships and building networks.\nYou scored a 3.6.\nYou may find emotionally charged interactions with others awkward and\nchallenging.\nWhat you can do:\n• Be aware of the message your body language is communicating\n• Ask those you admire for feedback about your interpersonal style.\n• Take responsibility for yourself by using \"I feel\" statements.\n• Appeal to others' uniqueness, build on mutual interests and show a\ngenuine curiosity for others' well-being.\n• Allow others to occasionally take the lead so you can learn from their\nleadership style.\n• Learn a person's name when you meet them and practice memory\ntechniques to retain that information.\n• Maintain eye contact and show interest in what others are saying.\n• Find an area of common ground to discuss by asking questions about\nthe other person.\n• Seek quality, rather than quantity, in your social bonds.\n• Realize that emotions play a strong role in our life. Understanding their\neffects will enable you to effectively lead and interact with others.\n• Join a professional association or special interest group to practice\nconnecting and communicating with others.\nCopyright © 2015, Dr. Izzy Justice and Target Training International, Ltd. 53"
  },
  {
    "page": 55,
    "title": "Emotional Quotient™ Wheel",
    "content": "Emotional Quotient™ Wheel\n3-20-2015\nT\nPERSON\nSELF REGULATION\nA\nSELF-AWARENESS\n3.0\nMOTIVATION\n6.2\n3.6\nSOCIAL SKILLS\nINTE\nRPERSON AL\nEMPATHY\nT: 6:20\nCopyright © 2015, Dr. Izzy Justice and Target Training International, Ltd. 54"
  },
  {
    "page": 56,
    "title": "Introduction Blending Behaviors, Motivators and EQ for Success",
    "content": "Introduction Blending Behaviors, Motivators and EQ for Success\nMaximizing the effectiveness of one's behavioral style can be a difficult maze to navigate\nin the workplace, especially in situations where \"behavioral labels\" are assigned. Often a\nteam will have muitiple people with the same behavioral styles faced with the same\nsituation, yet they come across differently.\nFor years, TT has educated the corporate world on behaviors, or the \"how\" of people's\nactions; meanwhile, motivators drive those actions, or \"why\" they do what they do. This\nhas explained the difference in actions for decades. However, recent research has led to\nthe discovery of people with similar behaviors and motivators, yet they still respond\ndifferently to situations, especially when the situations are emotionally charged\nWhy is this? The answer is often found within a person's Emotional Intelligence.\nUnderstanding a person's EQ and applying this information to behaviors and motivators\ncan not only expand the working language and communication of an organization, but\ncan help an individual successfully navigate the workplace maze and feel a sense of\naccomplishment and reward from doing so.\nTel. 937-597-4507 Email-CartaNeer@hotmail.com\nCopyright © 2006-2015. Target Training International, Ltd. 55"
  },
  {
    "page": 57,
    "title": "Blending Behaviors, Motivators and EQ",
    "content": "Blending Behaviors, Motivators and EQ\nfor Success\nPeople who understand and appreciate themselves as unique individuals and can\napply that same understanding and appreciation to others are more successful. This\npage is designed to connect behavioral strengths, motivational drives and a person's\nlevel of Emotional Intelligence in order to propel his or her ability to navigate the\nday-to-day situations of the business landscape.\nKyle has a low level of Self-Awareness. He doesn't tend to recognize\nmental and physical changes in how he is feeling. Coupled with his high\n\"Steadiness\" behavioral style, these feelings will be managed purely on a\nbehavioral basis. People with a high \"Steadiness\" tend to be methodical,\nsincere and willing to accommodate the needs of others, and they may\nsuppress their feelings when particular triggers are ignited without even\nrealizing it. They can become overly possessive with information and even\nstubborn in emotionally charged situations, and they may be unaware of the\nincreased intensity being displayed.\nKyle has a low level of Self-Regulation. He may not be able to temper\nresponses and reactions to emotionally charged events. Possessing a high\n\"Steadiness\" behavioral style indicates that Kyle would be non-demonstrative,\npossessive of information and will want to avoid conflict. However, with low\nSelf-Regulation, the typical behavioral characteristics may be intensified\nslightly, and this can have a negative impact on communications with others.\nBy understanding his steadiness behavior and how it impacts the\ncommunication flow with others, Kyle would benefit from understanding how to\nadapt this communication style for a more positive outcome. Be careful in\ninstances where the topic at hand directly relates to Kyle's Individualistic and\nAesthetic motivators in particular. The ability for him to utilize his knowledge\nof his behaviors will be hindered when a perceived threat to his drivers is\npresent.\nKyle has a low level of Motivation. He has a below average amount of\nmotivation and passion to work for reasons that don't satisfy his Individualistic\nand Aesthetic drivers. This motivation is an internal drive to achieve the goal;\nhowever, with motivation being below average, it's imperative to utilize an\nexternal driver or \"carrot\" to chase. Engagement and superior performance\ncan be achieved if and when his Individualistic and Aesthetic drivers have the\npotential to be satisfied through his career.\nCopyright © 2006-2015. Target Training International, Ltd. 56"
  },
  {
    "page": 58,
    "title": "Blending Behaviors, Motivators and EQ",
    "content": "Blending Behaviors, Motivators and EQ\nfor Success\nKyle has a low level of Empathy. He may not be able to anticipate how\nothers will receive information or react to a situation. If he is able to harness\nthis information, it will increase his ability to see things from someone else's\nperspective. Kyle typically views things from a Individualistic perspective,\nwhereas not all people filter information from this viewpoint. Developing the\nability to step out of this Individualistic mindset will be key to help\norganizational leaders create a stable and predictable organization which his\n\"Steadiness\" behavioral style is looking for.\nKyle has a low level of Social Skills. He may have difficulty managing\nrelationships and maintaining networks. Kyle has the ability to maintain\nrelationships with others that possess similar motivators, as they filter\ncommunication from the same viewpoint. His Individualistic and Aesthetic\ndrivers are his primary areas of interest, and he will do best in maintaining\nrelationships that directly lead to the satisfaction of these passions\nBehaviorally, Kyle prefers a warm and sincere approach. In addition, he wants\npersonal assurance and guarantees that can and will be delivered upon.\nBased on his development level of Social Skills, he may have difficulty\nadapting his communication style to meet the needs of the relationship and will\nhave the most success with this adaptation in relationships that lead to the\nsatisfaction of his Individualistic and Aesthetic drivers.\nCopyright © 2006-2015. Target Training International, Ltd. 57"
  }
];
