name: Build and Deploy

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

# Set minimal permissions for the GitHub token
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js with the latest LTS version and enable caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      # Install dependencies using npm ci for faster, reliable builds
      - name: Install dependencies
        run: npm ci

      # Build the static site
      - name: Build site
        run: npm run build

      # Deploy to GitHub Pages using peaceiris/actions-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: false
          force_orphan: false